### ISSUE TITLE
how to check if brotli file exists

### ISSUE THREAD

**Issue by alecklandgraf** [sjnam/lua-resty-brotli#2]
Hi there, I was wondering if it's possible to also check if the brotli file exists. e.g. this file `ngx.req.set_uri(ngx.var.uri..".br")`

I can't seem to find an easy way with lua in nginx to test this.

This would be useful as a way to enable a similar feature set to the static broli nginx brotli module provided by google, including only serving specific file types compressed as brotli, like `js,css`

It would also allow a graceful fallback if brotli files are not created during a build process.

best,
Aleck

**Comment by sjnam** [comment]
Hi, @alecklandgraf 
nginx variable **$document_root** is the name of your document root directory,
and you can check if a file exists in the document root directory.

```lua
content_by_lua_block {
    local f = io.open(ngx.var.document_root..ngx.var.uri..".br", "r")
    if not f then
       ngx.say("not exist")
    else
       io.close(f)
       ngx.say("file exists")
    end
}
```
